"""Add task and document models

Revision ID: 9eb66a668f70
Revises: 7bd79ac403e9
Create Date: 2025-09-30 10:11:14.343162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9eb66a668f70'
down_revision = '7bd79ac403e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'),
               type_=sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'),
               existing_nullable=False)
        batch_op.alter_column('assigned_to',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('tasks_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'units', ['unit_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['assigned_to'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tasks_ibfk_1'), 'staff', ['assigned_to'], ['id'])
        batch_op.alter_column('assigned_to',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'),
               type_=mysql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'),
               existing_nullable=False)
        batch_op.drop_column('unit_id')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
